apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: honduras-solicitude-volume
  namespace: kube-honduras
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: managed-premium
